version: '3.8'
name: musicshop

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://symfony:symfony@db:5432/app_db
    command: >
      sh -c "
        composer install &&
        php bin/console doctrine:migrations:migrate --no-interaction &&
        php -S 0.0.0.0:8000 -t public
      "

  db:
    image: postgres:15
    container_name: symfony_db
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: app_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
